# This is a basic workflow to help you get started with Actions

name: lambda-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
      name: deploy lambda function
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: testdeploy
          source: "index.js Readme.md"
